[EroProfile] Fix 403 (due to bad URL)
Before:

$ python test/test_download.py TestDownload.test_EroProfile
...
ERROR: unable to download video data: HTTP Error 403: Forbidden

After:

$ python test/test_download.py TestDownload.test_EroProfile
...
OK