Fix utils.py for PyPy on Windows
The line
```python
from __future__ import unicode_literals
```
introduced in commit [e868a12e77c3f91054cb16ad1032102b58746c16](https://github.com/rg3/youtube-dl/commit/e868a12e77c3f91054cb16ad1032102b58746c16) broke youtube-dl for PyPy on Windows, making it unable to locate WinAPI functions.
Error: "TypeError: function name must be a string or integer"

Adding "b" prefix to strings with WinAPI function names fixes it.